2025-08-20 09:27:42 [INFO    ] src.utils.excel: Logger configurado. Arquivo de log: logs/catalog_20250820_092742.log
2025-08-20 09:27:42 [INFO    ] src.utils.images: Logger configurado. Arquivo de log: logs/catalog_20250820_092742.log
2025-08-20 09:27:42 [INFO    ] __main__: Logger configurado. Arquivo de log: logs/catalog_20250820_092742.log
2025-08-20 09:27:42 [INFO    ] __main__: Iniciando geração do catálogo em PDF...
2025-08-20 09:27:42 [INFO    ] src.utils.excel: Carregando planilha: data/produtos.xlsx
2025-08-20 09:27:42 [INFO    ] src.utils.excel: 575 produtos após remover valores nulos
2025-08-20 09:27:42 [INFO    ] __main__: Planilha de produtos carregada com 575 itens.
2025-08-20 09:27:42 [INFO    ] src.utils.excel: Carregando planilha de imagens: data/base_imagens.xlsx
2025-08-20 09:27:42 [WARNING ] src.utils.excel: Foram encontradas e removidas 1197 SKUs duplicadas na base de imagens.
2025-08-20 09:27:42 [INFO    ] src.utils.excel: 1228 links de imagem e fornecedor válidos encontrados
2025-08-20 09:27:42 [INFO    ] __main__: Planilha de links de imagens carregada com 1228 registros.
2025-08-20 09:27:42 [ERROR   ] __main__: Erro fatal ao gerar catálogo: 'SKU'
Traceback (most recent call last):
  File "C:\Users\gustavo\Documents\Automation project\Catalogue-Automation\src\main.py", line 59, in main
    df = df.merge(img_links_df, how="left", left_on=c_sku, right_on="SKU")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gustavo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 10839, in merge
    return merge(
           ^^^^^^
  File "C:\Users\gustavo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\reshape\merge.py", line 170, in merge
    op = _MergeOperation(
         ^^^^^^^^^^^^^^^^
  File "C:\Users\gustavo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\reshape\merge.py", line 794, in __init__
    ) = self._get_merge_keys()
        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gustavo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\reshape\merge.py", line 1298, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gustavo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\generic.py", line 1911, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'SKU'
