2025-08-14 10:50:58 [INFO    ] utils.excel: Logger configurado. Arquivo de log: logs/catalog_20250814_105058.log
2025-08-14 10:50:58 [INFO    ] utils.images: Logger configurado. Arquivo de log: logs/catalog_20250814_105058.log
2025-08-14 10:50:58 [INFO    ] catalog_builder: Logger configurado. Arquivo de log: logs/catalog_20250814_105058.log
2025-08-14 10:50:58 [INFO    ] __main__: Logger configurado. Arquivo de log: logs/catalog_20250814_105058.log
2025-08-14 10:50:58 [INFO    ] __main__: Iniciando geração do catálogo com layout default
2025-08-14 10:50:58 [INFO    ] catalog_builder: Iniciando geração do catálogo...
2025-08-14 10:50:58 [ERROR   ] utils.excel: Erro ao carregar dados de produtos: [Errno 2] No such file or directory: 'data/products.xlsx'
2025-08-14 10:50:58 [ERROR   ] __main__: Erro fatal ao gerar catálogo: [Errno 2] No such file or directory: 'data/products.xlsx'
Traceback (most recent call last):
  File "c:\Users\gustavo\Documents\Automation project\src\main.py", line 66, in main
    build_catalog(args, layout_config)
  File "c:\Users\gustavo\Documents\Automation project\src\catalog_builder.py", line 133, in build_catalog
    df, c_sku, c_nome, c_cat, c_img = load_product_data(args.excel)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\gustavo\Documents\Automation project\src\utils\excel.py", line 17, in load_product_data
    df = pd.read_excel(path)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gustavo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\excel\_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "C:\Users\gustavo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\excel\_base.py", line 1550, in __init__
    ext = inspect_excel_format(
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gustavo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\excel\_base.py", line 1402, in inspect_excel_format
    with get_handle(
         ^^^^^^^^^^^
  File "C:\Users\gustavo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/products.xlsx'
